version: '3.9'
name: intesys-codylab-challenge-all-you-can-fix
services:
  shipping-datasource:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5433:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      org.springframework.boot.ignore: true
  wiremock:
    image: wiremock/wiremock:3.9.1
    container_name: wiremock
    ports:
      - "9990:8080"
    environment:
      - WIREMOCK_PORT=9990
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
